apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      container:
      - name: redis
        image: redis:4.0.2
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      # volumeClaimTemplates:
      # - metadata:
      #     name: redis-data
      #   spec:
      #     accessModes:
      #     - ReadWriteOnce
      #     resources:
      #       requests:
      #         storage: 1Gi
      #     storageClassName: your-storage-class

apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  selector:
    app: redis-master  
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
